export const lang = {
	English: {
		login: "Login",
		"Please Enter Below Details": "Please Enter Below Details",
		"Welcome to": "Welcome to",
		"Swasth Sahayak": "Swasth Sahayak",
		"Forgot Password": "Forgot Password",
		"Please Enter Below Details": "Please Enter Below Details",
		"Get OTP": "Get OTP",
		"Enter Employee Email": "Enter Employee Email",
		"Enter Password": "Enter Password",
		"Forgot Password": "Forgot Password ?",
		Home: "Home",
		Register: "Register",
		"Find Patient": "Find Patient",
		Profile: "Profile",
		"Sector Data": "Sector Data",
	},
	Hindi: {
		login: "लॉग इन",
		"Please Enter Below Details": "कृपया नीचे विवरण दर्ज करें",
		"Welcome to": "आपका स्वागत है",
		"Swasth Sahayak": "स्वास्थ्य सहायक",
		"Forgot Password": "पासवर्ड भूल गए",
		"Please Enter Below Details": "कृपया नीचे विवरण दर्ज करें",
		"Get OTP": "OTP प्राप्त करें",
		"Enter Employee Email": "कर्मचारी ईमेल दर्ज करें",
		"Enter Password": "पास वर्ड दर्ज करें",
		"Forgot Password": "पासवर्ड भूल गए ?",
		Home: "होम",
		Register: "पंजीकरण",
		"Find Patient": "रोगी खोजें",
		Profile: "प्रोफ़ाइल",
		"Sector Data": "सेक्टर डेटा",
	},
};
