export const lang = {
	English: {
		login: "Login",
		"Please Enter Below Details": "Please Enter Below Details",
		"Welcome to": "Welcome to",
		"Swasth Sahayak": "Swasth Sahayak",
		"Forgot Password": "Forgot Password",
		"Please Enter Below Details": "Please Enter Below Details",
		"Get OTP": "Get OTP",
		"Enter Employee Email": "Enter Employee Email",
		"Enter Password": "Enter Password",
		"Forgot Password": "Forgot Password ?",
		Home: "Home",
		Register: "Register",
		"Find Patient": "Find Patient",
		Profile: "Profile",
		"Sector Data": "Sector Data",
		"Enter OTP": "Enter OTP",
		"Verify OTP": "Verify OTP",
		"Confirm Password": "Confirm Password",
		"Reset this as new password": "Reset this as new password",
		"Not Downloaded": "Not downloaded yet.",
		"Download Sector Data": "Download Sector Data",
		"Follow-Up Schedule": "Follow-up Schedule",
		"Visited": "Visited",
		"View Patient Records": "View Patient Records",
		"Free Visits On": "Free visits on :",
		"Sector 12": "Sector 12",
		"Patient Token": "Patient Token",
		"Enter Patient Token": "Enter Patient Token",
		"Submit": "Submit",
		"Enter ABHA ID": "Enter ABHA ID",
		"Register Patient": "Register Patient",
		"Patient Registeration": "Patient Registration",
	},
	Hindi: {
		login: "लॉग इन",
		"Please Enter Below Details": "कृपया नीचे विवरण दर्ज करें",
		"Welcome to": "आपका स्वागत है",
		"Swasth Sahayak": "स्वास्थ्य सहायक",
		"Forgot Password": "पासवर्ड भूल गए",
		"Please Enter Below Details": "कृपया नीचे विवरण दर्ज करें",
		"Get OTP": "OTP प्राप्त करें",
		"Enter Employee Email": "कर्मचारी ईमेल दर्ज करें",
		"Enter Password": "पास वर्ड दर्ज करें",
		"Forgot Password": "पासवर्ड भूल गए ?",
		Home: "होम",
		Register: "पंजीकरण",
		"Find Patient": "रोगी खोजें",
		Profile: "प्रोफ़ाइल",
		"Sector Data": "सेक्टर डेटा",
		"Enter OTP": "OTP दर्ज करें",
		"Verify OTP": "OTP सत्यापित करें",
		"Confirm Password": "पासवर्ड पुष्टि करें",
		"Reset this as new password": "इसे नये पासवर्ड के रूप में रीसेट करें",
		"Not Downloaded": "अभी डाउनलोड नहीं किया गया",
		"Download Sector Data": "सेक्टर डेटा डाउनलोड करें",
		"Follow-Up Schedule": "अनुवर्ती अनुसूची",
		"Visited": "दौरा किया",
		"View Patient Records": "रोगी के रिकार्ड्स देखे",
		"Free Visits On": "निःशुल्क विज़िट :",
		"Sector 12": "सेक्टर 12",
		"Patient Token":"रोगी टोकन",
		"Enter Patient Token": "रोगी टोकन दर्ज करें",
		"Submit": "सबमिट करें",
		"Enter ABHA ID":"आभा आईडी दर्ज करें",
		"Register Patient": "रोगी पंजीकरण करें",
		"Patient Registeration": "रोगी पंजीकरण ",
	},
};
