export const lang = {
	English: {
		login: "Login",
		"Please Enter Below Details": "Please Enter Below Details",
		"Welcome to": "Welcome to",
		"Swasth Sahayak": "Swasth Sahayak",
		"Forgot Password": "Forgot Password",
		"Please Enter Below Details": "Please Enter Below Details",
		"Get OTP": "Get OTP",
		"Enter Employee Email": "Enter Employee Email",
		"Enter Password": "Enter Password",
		"Forgot Password": "Forgot Password ?",
		Home: "Home",
		Register: "Register",
		"Find Patient": "Find Patient",
		Profile: "Profile",
		"Sector Data": "Sector Data",
		"Enter OTP": "Enter OTP",
		"Verify OTP": "Verify OTP",
		"Confirm Password": "Confirm Password",
		"Reset this as new password": "Reset this as new password",
		"Not Downloaded": "Not downloaded yet.",
		"Download Sector Data": "Download Sector Data",
		"Follow-Up Schedule": "Follow-up Schedule",
		Visited: "Visited",
		"Not Visited": "Not Visited",
		"View Patient Records": "View Patient Records",
		"Free Visits On": "Free visits on :",
		"Sector 12": "Sector 12",
		"Patient Token": "Patient Token",
		"Enter Patient Token": "Enter Patient Token",
		Submit: "Submit",
		"Enter ABHA ID": "Enter ABHA ID",
		"Register Patient": "Register Patient",
		"Patient Registeration": "Patient Registration",
		Neurosurgeon: "Neurosurgeon",
		"Reset Password": "Reset Password",
		Logout: "Logout",
		"Patient Dashboard": "Patient Dashboard",
		"Current Diagnose": "Current Diagnosis",
		"Ongoing medication orders": "Ongoing medication orders",
		"added a comment on Followup": "Added a comment on follow up",
		"Enter Text": "Enter text here...",
		"Proceed to Diagnosis": "Proceed to Diagnosis",
		"Diagnose History": "Diagnosis History",
		"Questionnaire →": "Questionnaire →",
		Date: "Date",
		Disease: "Disease",
		"Questionnaire Score": "Questionnaire Score",
		Prescription: "Prescription",
		"A doctor is a person who heals, while a nurse is a person who cares":
			"A doctor is a person who heals, while a nurse is a person who cares",
		Hello: "Hello",
		"First Name": "First Name",
		"Last Name": "Last Name",
		Male: "Male",
		Female: "Female",
		Other: "Other",
		"Abha-ID": "Abha-ID",
		"Phone Number": "Phone Number",
		Address: "Address",
		Sector: "Sector",
		Pincode: "Pincode",
		Questionnaire: "Questionnaire",
		Prescription: "Prescription",
		"Added new Follow-up Instructions":
			"Added new Follow-up Instructions",
		"Print via Bluetooth": "Print via Bluetooth",
		"Back to Patient Dashboard": "Back to Patient Dashboard",
		"Ask Questionnaire": "Ask Questionnaire",
	},
	Hindi: {
		login: "लॉग इन",
		"Please Enter Below Details": "कृपया नीचे विवरण दर्ज करें",
		"Welcome to": "आपका स्वागत है",
		"Swasth Sahayak": "स्वास्थ्य सहायक",
		"Forgot Password": "पासवर्ड भूल गए",
		"Please Enter Below Details": "कृपया नीचे विवरण दर्ज करें",
		"Get OTP": "OTP प्राप्त करें",
		"Enter Employee Email": "कर्मचारी ईमेल दर्ज करें",
		"Enter Password": "पास वर्ड दर्ज करें",
		"Forgot Password": "पासवर्ड भूल गए ?",
		Home: "होम",
		Register: "पंजीकरण",
		"Find Patient": "रोगी खोजें",
		Profile: "प्रोफ़ाइल",
		"Sector Data": "सेक्टर डेटा",
		"Enter OTP": "OTP दर्ज करें",
		"Verify OTP": "OTP सत्यापित करें",
		"Confirm Password": "पासवर्ड पुष्टि करें",
		"Reset this as new password": "इसे नये पासवर्ड के रूप में रीसेट करें",
		"Not Downloaded": "अभी डाउनलोड नहीं किया गया",
		"Download Sector Data": "सेक्टर डेटा डाउनलोड करें",
		"Follow-Up Schedule": "अनुवर्ती अनुसूची",
		Visited: "दौरा किया",
		"Not Visited": "देखा नहीं गया",
		"View Patient Records": "रोगी के रिकार्ड्स देखे",
		"Free Visits On": "निःशुल्क विज़िट :",
		"Sector 12": "सेक्टर 12",
		"Patient Token": "रोगी टोकन",
		"Enter Patient Token": "रोगी टोकन दर्ज करें",
		Submit: "सबमिट करें",
		"Enter ABHA ID": "आभा आईडी दर्ज करें",
		"Register Patient": "रोगी पंजीकरण करें",
		"Patient Registeration": "रोगी पंजीकरण ",
		Neurosurgeon: "न्यूरोसेजन",
		"Reset Password": "पासवर्ड रीसेट करें",
		Logout: "लॉग आउट",
		"Patient Dashboard": "रोगी डैशबोर्ड",
		"Current Diagnose": "वर्तमान निदान",
		"Ongoing medication orders": "वर्तमान निदान",
		"Questionnaire →": "प्रश्नावली →",
		Questionnaire: "प्रश्नावली",
		Prescription: "नुस्खा",
		"added a comment on Followup": "फॉलोअप पर एक टिप्पणी जोड़ी",
		"Enter Text": "पाठ दर्ज करें...",
		"Proceed to Diagnosis": "निदान के लिए आगे बढ़ें",
		"Diagnose History": "इतिहास का निदान करें",
		Date: "तारीख",
		Disease: "बीमारी",
		"Questionnaire Score": "प्रश्नावली स्कोर",
		Prescription: "प्रस्ताव",
		"A doctor is a person who heals, while a nurse is a person who cares":
			"डॉक्टर वह व्यक्ति है जो उपचार करता है, जबकि नर्स वह व्यक्ति है किसे पड़ी है",
		Hello: "नमस्ते",
		"First Name": "पहला नाम",
		"Last Name": "उपनाम",
		Male: "पुरुष",
		Female: "महिला",
		Other: "अन्य",
		"Abha-ID": "अवा-आईडी",
		"Phone Number": "फ़ोन नंबर",
		Address: "पता",
		Sector: "क्षेत्र",
		Pincode: "पिन कोड",
		"Added new Follow-up Instructions": "नए अनुवर्ती निर्देश जोड़े गए",
		"Print via Bluetooth": "ब्लूटूथ के माध्यम से प्रिंट करें",
		"Back to Patient Dashboard": "रोगी डैशबोर्ड पर वापस जाएँ",
		"Ask Questionnaire": "रश्नावली पूछें",
	},
};
