export default AppStyles = {
	color: {
		red: "#f40d30",
		primaryLight: "#d9f0ef",
		primary: "#40B5AD",
		// primary: "blue",
		primaryDark: "#0073C2",
		green: "#009879",
		yellow: "#FFDF00",
		lightPink: "#F987C5",
		pink: "#F62088",
		gold: "#FFB000",
		redHover: "#f85a40",
		black: "#000000",
		darkRed: "#8b0000",
	},
	primaryBtn: {
		backgroundColor: "#40B5AD",
		maxWidth: 300,
		borderRadius: 7,
		paddingVertical: 15,
		paddingHorizontal: 25,
		marginVertical: 15,
		marginHorizontal: 20,
	},
	redBtn: {
		backgroundColor: "#f40d30",
		maxWidth: 300,
		borderRadius: 7,
		paddingVertical: 15,
		paddingHorizontal: 25,
		marginVertical: 15,
		marginHorizontal: 20,
	},
	goldBtn: {
		backgroundColor: "#FFB000",
		maxWidth: 300,
		borderRadius: 7,
		paddingVertical: 15,
		paddingHorizontal: 25,
		marginVertical: 15,
		marginHorizontal: 20,
	},
	darkRedBtn: {
		backgroundColor: "#8b0000",
		maxWidth: 300,
		borderRadius: 7,
		paddingVertical: 15,
		paddingHorizontal: 25,
		marginVertical: 15,
		marginHorizontal: 20,
	},
	primaryBtnText: {
		color: "white",
		textAlign: "center",
		fontSize: 20,
		fontWeight: "600",
		textAlignVertical: "center",
	},
	primaryBtnLargeText: {
		color: "white",
		textAlign: "center",
		fontSize: 32,
		fontWeight: "600",
	},
	line: {
		backgroundColor: "#000",
		height: 2,
		width: "80%",
		alignSelf: "center",
		marginBottom: 10,
	},
	btn: {
		alignSelf: "center",
		margin: 5,
	},
	subHeading: {
		fontSize: 24,
		marginVertical: 20,
		fontWeight: "700",
	},
};
